var subject = require('./subject.js')
var mock = require('mock-fs');
subject.inc('',7.448712140321732);
subject.inc(NaN,2.019068447407335);
subject.inc('',undefined);
subject.inc(NaN,undefined);
subject.inc('',undefined);
subject.weird('','','',"strict");
mock({"path/fileExists":{},"pathContent":{"file1":"text content"}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"pathContent":{"file1":"text content"}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"path/fileExists":{}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
subject.normalize('');
subject.format('','','');
subject.blackListNumber('');
